name: 'Preview Site: Build and Deploy to Netlify'

on:
  workflow_dispatch:
  push:
    branches: [ 'develop' ]
    paths: ['pulter-site/**', 'pulter-poems/**']

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
#       - name: Check out the repo
#         uses: actions/checkout@v1
#         with:
#           submodules: true

#       - name: Prepare Node 18
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - run: yarn
#       - run: npm i -g gulp-cli@latest
#       - run: npm run build

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.weinberg.northwestern.edu:443
          role: MADS-S3-dev
          method: jwt-github
          secrets: |
            platforms-kvv2/data/secrets/MADS-S3/dev access_key | AWS_ACCESS_KEY_ID ;
            platforms-kvv2/data/secrets/MADS-S3/dev secret_key | AWS_SECRET_ACCESS_KEY ;

      - name: Deploy to S3 
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          publish-dir: 'dist'
          production-deploy: true
          deploy-message: Triggered from Github Actions by @${{ github.actor }}.
        env:
          aws_key_id: "${{  steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key: "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
          aws_bucket: "mads-static-sites-dev-pulterproject-dev"
          source_dir: 'dist'
        timeout-minutes: 1
